// TRIGER CATEGORY

DELIMITER$$
CREATE OR REPLACE TRIGGER ID_CATEGORY 
BEFORE INSERT ON categories
FOR EACH ROW
BEGIN 
	INSERT INTO tsequancecategory VALUES ("");
	SELECT MAX(category_id) INTO @ID
	FROM tsequancecategory;
	SET new.CATEGORY_ID=CONCAT('CAT',LPAD(@ID,2,'0'));
END$$
DELIMITER ;

// TRIGER CUSTOMER

DELIMITER$$
CREATE OR REPLACE TRIGGER ID_CUSTOMER
BEFORE INSERT ON customer
FOR EACH ROW
BEGIN 
	INSERT INTO tsequancecustomer2 VALUES ("");
	SELECT MAX(customer_id) INTO @ID
	FROM tsequancecustomer2;
	SET new.CUSTOMER_ID=CONCAT('CUS',LPAD(@ID,3,'0'));
END$$
DELIMITER ;

// TRIGER PRODUCT

DELIMITER$$
CREATE OR REPLACE TRIGGER ID_PRODUCT
BEFORE INSERT ON product
FOR EACH ROW
BEGIN 
	INSERT INTO tsequanceproduct VALUES ("");
	SELECT MAX(product_id) INTO @ID
	FROM tsequanceproduct;
	SET new.PRODUCT_ID=CONCAT('PRO',LPAD(@ID,3,'0'));
END$$
DELIMITER ;

// TRIGER TUSER

DELIMITER$$
CREATE OR REPLACE TRIGGER ID_USER
BEFORE INSERT ON USER
FOR EACH ROW
BEGIN 
	INSERT INTO tsequanceuser VALUES ("");
	SELECT MAX(user_id) INTO @ID
	FROM tsequanceuser;
	SET new.USER_ID=CONCAT('US',LPAD(@ID,3,'0'));
END$$
DELIMITER ;

INSERT INTO 